trigger:
- main

schedules:
- cron: "0 12 * * 4"   # каждый четверг в 12:00 (UTC)
  displayName: Weekly Thursday Noon Run
  branches:
    include:
    - main
  always: true  # запускается даже без новых коммитов

pool:
  name: Default

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
